# Generated by Django 3.2.8 on 2022-05-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='contactUs',
        ),
        migrations.RenameModel(
            old_name='jobs',
            new_name='job',
        ),
        migrations.RenameModel(
            old_name='testimonials',
            new_name='testimonial',
        ),
    ]
