# Generated by Django 3.2.8 on 2022-05-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220512_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='brief',
        ),
        migrations.AddField(
            model_name='job',
            name='batch',
            field=models.CharField(default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(default='sde', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='photo',
            field=models.ImageField(upload_to='company_images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='teams/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(upload_to='testimonials/'),
        ),
    ]
