# Generated by Django 3.2.8 on 2022-05-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220513_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(default='$', max_length=20),
        ),
    ]
