# Generated by Django 3.2.8 on 2022-05-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='stars',
            field=models.IntegerField(default=5),
        ),
    ]
