# Generated by Django 3.2.8 on 2022-05-13 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_alter_testimonial_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_offer', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('company_name', models.CharField(max_length=50)),
                ('work_mode_preference', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='pictures/')),
                ('notice_period', models.IntegerField(default=0)),
                ('current_ctc', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('expected_salary', models.IntegerField()),
                ('status', models.CharField(default='under process', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
