# Generated by Django 3.2.8 on 2022-05-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='r@fr', max_length=254),
        ),
    ]
