# Generated by Django 3.2.8 on 2022-05-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_registration_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='expected_salary',
            new_name='expected_ctc',
        ),
        migrations.AddField(
            model_name='registration',
            name='area_code',
            field=models.IntegerField(default=0),
        ),
    ]
