# Generated by Django 3.2.8 on 2022-05-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20220515_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='area_code',
            field=models.IntegerField(),
        ),
    ]
