# Generated by Django 3.2.8 on 2022-05-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_registration_area_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='have_offer',
            new_name='open_to_relocate',
        ),
    ]
