# Generated by Django 3.2.8 on 2022-05-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_have_offer_registration_open_to_relocate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='mobile_number',
            new_name='contact_number',
        ),
    ]
