# Generated by Django 3.2.8 on 2022-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_mobile_number_registration_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='hgf', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(max_length=500),
        ),
    ]
